/**
 * 題材板塊成分（人工維護）。
 *
 * 分類依據：
 * - 依「市場熱門題材／產業鏈角色」分組，不是證交所官方產業分類代碼
 * - 靈感接近題材／族群題材切法：同一供應鏈或同一催化事件常一起被點名的股票
 * - 成分以流動性與代表性為主（權值、族群指標股、常出現在券商題材清單者）
 * - 一檔股票可同時出現在多個相關板塊（例如廣達可在 AI 伺服器與 EMS）
 * - 非完整宇宙，刻意聚焦可讀的核心名單，而非列出該產業所有上市櫃公司
 */

export type SectorMember = { code: string; name: string };

export type SectorDef = {
  id: string;
  name: string;
  /** 分類說明（給小百科／頁面提示用） */
  basis: string;
  members: SectorMember[];
};

export const SECTOR_UNIVERSE: SectorDef[] = [
  {
    id: "ai-server",
    name: "AI 伺服器組裝",
    basis: "雲端／AI 伺服器 ODM／組裝與機殼散熱指標股",
    members: [
      { code: "6669", name: "緯穎" },
      { code: "2382", name: "廣達" },
      { code: "3231", name: "緯創" },
      { code: "2356", name: "英業達" },
      { code: "2376", name: "技嘉" },
      { code: "2324", name: "仁寶" },
      { code: "2353", name: "宏碁" },
      { code: "2357", name: "華碩" },
      { code: "3017", name: "奇鋐" },
      { code: "3706", name: "神基" },
      { code: "6414", name: "樺漢" },
      { code: "2395", name: "研華" },
    ],
  },
  {
    id: "liquid-cooling",
    name: "液冷散熱",
    basis: "AI 伺服器液冷、均熱板、風扇與機構散熱鏈",
    members: [
      { code: "3017", name: "奇鋐" },
      { code: "3324", name: "雙鴻" },
      { code: "6235", name: "華孚" },
      { code: "2421", name: "建準" },
      { code: "3653", name: "健策" },
      { code: "2465", name: "麗臺" },
      { code: "8255", name: "朋程" },
      { code: "3037", name: "欣興" },
      { code: "3483", name: "力致" },
      { code: "4540", name: "全球傳動" },
    ],
  },
  {
    id: "ems",
    name: "EMS 電子代工",
    basis: "電子代工／組裝代工（EMS／ODM）大型權值與指標股",
    members: [
      { code: "2317", name: "鴻海" },
      { code: "4938", name: "和碩" },
      { code: "2356", name: "英業達" },
      { code: "3231", name: "緯創" },
      { code: "2382", name: "廣達" },
      { code: "2357", name: "華碩" },
      { code: "2324", name: "仁寶" },
      { code: "2353", name: "宏碁" },
      { code: "3702", name: "大聯大" },
      { code: "3036", name: "文曄" },
      { code: "2347", name: "聯強" },
      { code: "2360", name: "致茂" },
    ],
  },
  {
    id: "pcb",
    name: "PCB 載板",
    basis: "印刷電路板、ABF／BT 載板與相關材料",
    members: [
      { code: "3037", name: "欣興" },
      { code: "8046", name: "南電" },
      { code: "2368", name: "金像電" },
      { code: "3189", name: "景碩" },
      { code: "2313", name: "華通" },
      { code: "2355", name: "敬鵬" },
      { code: "5469", name: "瀚宇博" },
      { code: "6213", name: "聯茂" },
      { code: "2383", name: "台光電" },
      { code: "4958", name: "臻鼎-KY" },
      { code: "3044", name: "健鼎" },
      { code: "6274", name: "台燿" },
    ],
  },
  {
    id: "foundry",
    name: "晶圓代工",
    basis: "晶圓代工與封測龍頭（半導體製造核心）",
    members: [
      { code: "2330", name: "台積電" },
      { code: "2303", name: "聯電" },
      { code: "3711", name: "日月光投控" },
      { code: "6770", name: "力積電" },
      { code: "5347", name: "世界" },
      { code: "4919", name: "新唐" },
      { code: "2449", name: "京元電子" },
      { code: "6239", name: "力成" },
    ],
  },
  {
    id: "advanced-packaging",
    name: "AI 先進封裝",
    basis: "CoWoS／先進封裝、測試與相關材料",
    members: [
      { code: "3711", name: "日月光投控" },
      { code: "6239", name: "力成" },
      { code: "2449", name: "京元電子" },
      { code: "3374", name: "精材" },
      { code: "3532", name: "台勝科" },
      { code: "6488", name: "環球晶" },
      { code: "6182", name: "合晶" },
      { code: "5483", name: "中美晶" },
      { code: "3016", name: "嘉晶" },
      { code: "3131", name: "弘塑" },
    ],
  },
  {
    id: "hbm-memory",
    name: "HBM／記憶體",
    basis: "DRAM／NAND／控制晶片與記憶體模組鏈",
    members: [
      { code: "2408", name: "南亞科" },
      { code: "2344", name: "華邦電" },
      { code: "8299", name: "群聯" },
      { code: "2451", name: "創見" },
      { code: "3260", name: "威剛" },
      { code: "4967", name: "十銓" },
      { code: "8271", name: "宇瞻" },
      { code: "3706", name: "神基" },
      { code: "2404", name: "漢唐" },
      { code: "3017", name: "奇鋐" },
    ],
  },
  {
    id: "ic-design",
    name: "IC 設計",
    basis: "IC 設計權值與 AI／高速傳輸相關設計股",
    members: [
      { code: "2454", name: "聯發科" },
      { code: "3034", name: "聯詠" },
      { code: "2379", name: "瑞昱" },
      { code: "4966", name: "譜瑞-KY" },
      { code: "3443", name: "創意" },
      { code: "5274", name: "信驊" },
      { code: "3661", name: "世芯-KY" },
      { code: "6415", name: "矽力*-KY" },
      { code: "2301", name: "光寶科" },
      { code: "3529", name: "力旺" },
      { code: "6531", name: "愛普*" },
      { code: "8261", name: "富鼎" },
    ],
  },
  {
    id: "semiconductor-equipment",
    name: "半導體設備材料",
    basis: "半導體製程設備、矽晶圓與特用材料",
    members: [
      { code: "3532", name: "台勝科" },
      { code: "3131", name: "弘塑" },
      { code: "3583", name: "辛耘" },
      { code: "6182", name: "合晶" },
      { code: "5483", name: "中美晶" },
      { code: "3016", name: "嘉晶" },
      { code: "6488", name: "環球晶" },
      { code: "3680", name: "家登" },
      { code: "6667", name: "信紘科" },
      { code: "6640", name: "均華" },
      { code: "7728", name: "創鑫智慧" },
      { code: "6290", name: "良維" },
    ],
  },
  {
    id: "smartphone",
    name: "智慧型手機",
    basis: "智慧手機代工、機構件、鏡頭與相機模組",
    members: [
      { code: "2317", name: "鴻海" },
      { code: "2474", name: "可成" },
      { code: "3008", name: "大立光" },
      { code: "3406", name: "玉晶光" },
      { code: "2354", name: "鴻準" },
      { code: "2385", name: "群光" },
      { code: "4938", name: "和碩" },
      { code: "2392", name: "正崴" },
      { code: "3653", name: "健策" },
      { code: "6278", name: "台表科" },
    ],
  },
  {
    id: "power-inductor",
    name: "功率電感／被動",
    basis: "被動元件、電感、電阻電容與電源相關",
    members: [
      { code: "2456", name: "奇力新" },
      { code: "2327", name: "國巨" },
      { code: "2492", name: "華新科" },
      { code: "2308", name: "台達電" },
      { code: "6176", name: "瑞儀" },
      { code: "6282", name: "康舒" },
      { code: "3042", name: "立通" },
      { code: "3090", name: "日電貿" },
      { code: "2428", name: "興勤" },
      { code: "6861", name: "睿生光電" },
    ],
  },
  {
    id: "networking",
    name: "網通與交換器",
    basis: "乙太網路交換、網通代工與電信營運",
    members: [
      { code: "2345", name: "智邦" },
      { code: "3706", name: "神基" },
      { code: "3596", name: "智易" },
      { code: "6285", name: "啟碁" },
      { code: "4904", name: "遠傳" },
      { code: "2412", name: "中華電" },
      { code: "3045", name: "台灣大" },
      { code: "5388", name: "中磊" },
      { code: "6442", name: "光聖" },
      { code: "4977", name: "眾達-KY" },
    ],
  },
  {
    id: "optical",
    name: "光通訊／矽光子",
    basis: "光模組、矽光子、光通訊元件與代工",
    members: [
      { code: "3363", name: "上詮" },
      { code: "4977", name: "眾達-KY" },
      { code: "6451", name: "訊芯-KY" },
      { code: "4979", name: "華星光" },
      { code: "3081", name: "聯亞" },
      { code: "6442", name: "光聖" },
      { code: "3231", name: "緯創" },
      { code: "3037", name: "欣興" },
      { code: "3711", name: "日月光投控" },
      { code: "3661", name: "世芯-KY" },
    ],
  },
  {
    id: "shipping",
    name: "航運",
    basis: "貨櫃、散裝與相關航運權值",
    members: [
      { code: "2603", name: "長榮" },
      { code: "2609", name: "陽明" },
      { code: "2615", name: "萬海" },
      { code: "2606", name: "裕民" },
      { code: "2637", name: "慧洋-KY" },
      { code: "2618", name: "長榮航" },
      { code: "2610", name: "華航" },
      { code: "5608", name: "四維航" },
      { code: "2605", name: "新興" },
      { code: "2636", name: "台驊投控" },
    ],
  },
  {
    id: "financials",
    name: "金融控股",
    basis: "金控權值股（銀行／保險／證券綜合）",
    members: [
      { code: "2881", name: "富邦金" },
      { code: "2882", name: "國泰金" },
      { code: "2891", name: "中信金" },
      { code: "2886", name: "兆豐金" },
      { code: "2884", name: "玉山金" },
      { code: "2880", name: "華南金" },
      { code: "2885", name: "元大金" },
      { code: "2883", name: "開發金" },
      { code: "2890", name: "永豐金" },
      { code: "2887", name: "台新金" },
      { code: "2892", name: "第一金" },
      { code: "5880", name: "合庫金" },
    ],
  },
  {
    id: "biotech",
    name: "生技醫藥",
    basis: "新藥、CDMO／製藥與醫材指標股",
    members: [
      { code: "4743", name: "合一" },
      { code: "6541", name: "泰福-KY" },
      { code: "1795", name: "美時" },
      { code: "4162", name: "智擎" },
      { code: "6472", name: "保瑞" },
      { code: "4119", name: "旭富" },
      { code: "1789", name: "神隆" },
      { code: "1760", name: "寶齡富錦" },
      { code: "6547", name: "高端疫苗" },
      { code: "6666", name: "羅麗芬-KY" },
    ],
  },
  {
    id: "green-energy",
    name: "綠能與儲能",
    basis: "太陽能、儲能、電力設備與綠能開發",
    members: [
      { code: "6869", name: "雲豹能源" },
      { code: "6443", name: "元晶" },
      { code: "3576", name: "聯合再生" },
      { code: "1513", name: "中興電" },
      { code: "1605", name: "華新" },
      { code: "1519", name: "華城" },
      { code: "1504", name: "東元" },
      { code: "6409", name: "旭隼" },
      { code: "6792", name: "詠業" },
      { code: "6781", name: "AES-KY" },
    ],
  },
  {
    id: "auto-electronics",
    name: "車用電子",
    basis: "車用感測、功率、連接與模組",
    members: [
      { code: "2231", name: "為升" },
      { code: "6271", name: "同欣電" },
      { code: "2392", name: "正崴" },
      { code: "8255", name: "朋程" },
      { code: "2247", name: "宏旭-KY" },
      { code: "3653", name: "健策" },
      { code: "2308", name: "台達電" },
      { code: "2456", name: "奇力新" },
      { code: "3037", name: "欣興" },
      { code: "2383", name: "台光電" },
    ],
  },
  {
    id: "panel",
    name: "面板與光學",
    basis: "面板、背光與光學鏡頭",
    members: [
      { code: "3481", name: "群創" },
      { code: "2409", name: "友達" },
      { code: "3008", name: "大立光" },
      { code: "3406", name: "玉晶光" },
      { code: "4935", name: "茂林-KY" },
      { code: "6176", name: "瑞儀" },
      { code: "6116", name: "彩晶" },
      { code: "3535", name: "晶彩科" },
      { code: "5490", name: "同亨" },
      { code: "8105", name: "凌巨" },
    ],
  },
  {
    id: "defense",
    name: "軍工航太",
    basis: "航太製造、造船與國防電子相關",
    members: [
      { code: "2634", name: "漢翔" },
      { code: "2208", name: "台船" },
      { code: "4572", name: "駐波" },
      { code: "8038", name: "長園科" },
      { code: "2498", name: "宏達電" },
      { code: "3023", name: "信邦" },
      { code: "2464", name: "盟立" },
      { code: "2236", name: "百達-KY" },
    ],
  },
];

export function allUniverseCodes(): string[] {
  const set = new Set<string>();
  for (const s of SECTOR_UNIVERSE) {
    for (const m of s.members) set.add(m.code);
  }
  return [...set];
}
